"""empty message

Revision ID: 3e33d33ad464
Revises: 40f9a1d8b9a5
Create Date: 2023-11-29 09:34:06.883480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e33d33ad464'
down_revision = '40f9a1d8b9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=150), nullable=False),
    sa.Column('hobby1', sa.String(length=150), nullable=False),
    sa.Column('hobby2', sa.String(length=150), nullable=False),
    sa.Column('hobby3', sa.String(length=150), nullable=False),
    sa.Column('hobby4', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hobby')
    # ### end Alembic commands ###
