"""empty message

Revision ID: 88a4a1245bfa
Revises: 9b6b9ea131f5
Create Date: 2023-11-30 11:00:13.853182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a4a1245bfa'
down_revision = '9b6b9ea131f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
