"""empty message

Revision ID: 9b6b9ea131f5
Revises: dfdf3919de45
Create Date: 2023-11-30 09:35:52.291998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6b9ea131f5'
down_revision = 'dfdf3919de45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hobby')
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_hobby_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hobby_user_id_user'), type_='foreignkey')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('create_date')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_hobby',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=150), nullable=False),
    sa.Column('hobby1', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hobby2', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hobby3', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hobby4', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_hobby_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
