"""empty message

Revision ID: a36cb7a1f46d
Revises: 88a4a1245bfa
Create Date: 2023-12-01 16:55:26.438120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36cb7a1f46d'
down_revision = '88a4a1245bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
