"""empty message

Revision ID: dfdf3919de45
Revises: 46220d4be995
Create Date: 2023-11-30 09:25:43.421934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdf3919de45'
down_revision = '46220d4be995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], name=op.f('fk_hobby_voter_hobby_id_hobby'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_hobby_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'hobby_id', name=op.f('pk_hobby_voter'))
    )
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_hobby_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hobby_user_id_user'), type_='foreignkey')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('create_date')
        batch_op.drop_column('user_id')

    op.drop_table('hobby_voter')
    # ### end Alembic commands ###
